version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name cicd-handson-app --s3-location s3://cicd-workfinal/artifact.zip --source .
artifacts:
  files:
    - '**/*'
  base-directory: src